"""Build screen_run_log.{jsonl,md} from the Claude Code subagent transcripts of the abstract screen.

Reads every subagent transcript in SUBAGENTS, keeps the ones whose first prompt is a screening
task, and records per agent run: batch, model(s) actually sent to the API, token usage summed
over all assistant turns, start/end time, and outcome (completed / failed, with the error).
Also copies the transcripts, gzipped, into screen_traces/.
"""
import collections, glob, gzip, json, os, re, shutil

HERE = os.path.dirname(os.path.abspath(__file__))
SUBAGENTS = os.path.expanduser(
    "~/.claude/projects/<project-dir>"
    "observables-darkmatterFM-dark-matter-model-registry/64912b51-5b5f-4588-a67d-751db700e2fe/subagents")
USAGE_KEYS = ("input_tokens", "cache_creation_input_tokens", "cache_read_input_tokens", "output_tokens")


def first_prompt(rows):
    for r in rows:
        if r.get("type") == "user":
            c = r["message"]["content"]
            return c if isinstance(c, str) else " ".join(x.get("text", "") for x in c if isinstance(x, dict))
    return ""


def main():
    runs = []
    os.makedirs(os.path.join(HERE, "screen_traces"), exist_ok=True)
    for f in sorted(glob.glob(os.path.join(SUBAGENTS, "agent-*.jsonl"))):
        rows = [json.loads(l) for l in open(f) if l.strip()]
        prompt = first_prompt(rows)
        m = re.search(r"NNN = (\d{3})|batch_(\d{3})\.jsonl", prompt)
        if "Screen" not in prompt and "screening arXiv" not in prompt or not m:
            continue
        batch = int(m.group(1) or m.group(2))
        meta_path = f.replace(".jsonl", ".meta.json")
        meta = json.load(open(meta_path)) if os.path.exists(meta_path) else {}
        usage, models, errors, n_turns = collections.Counter(), collections.Counter(), [], 0
        for r in rows:
            if r.get("type") != "assistant":
                continue
            msg = r.get("message", {})
            models[msg.get("model", "?")] += 1
            u = msg.get("usage") or {}
            if u:
                n_turns += 1
                for k in USAGE_KEYS:
                    usage[k] += u.get(k) or 0
            if r.get("isApiErrorMessage") or r.get("error"):
                errors.append(str(r.get("error") or msg.get("content"))[:300])
        text = json.dumps(rows[-1])[-2000:]
        failed = bool(errors) or "session limit" in text or "rate_limit" in text
        ts = [r["timestamp"] for r in rows if r.get("timestamp")]
        out = os.path.join(HERE, "screen_results", f"batch_{batch:03d}.jsonl")
        runs.append({
            "agent_id": rows[0].get("agentId"), "batch": batch,
            "models": dict(models), "effort": next((r.get("effort") for r in rows if r.get("effort")), None),
            "agent_type": meta.get("agentType") or meta.get("subagent_type"),
            "start": min(ts) if ts else None, "end": max(ts) if ts else None,
            "api_turns": n_turns, **{k: usage[k] for k in USAGE_KEYS},
            "total_tokens": sum(usage.values()),
            "outcome": "failed" if failed else "completed",
            "error": errors[0] if errors else (re.search(r"You've hit your session limit[^\"]*", text).group(0) if "session limit" in text else None),
            "prompt": prompt,
            "trace": f"screen_traces/agent-{rows[0].get('agentId')}.jsonl.gz",
        })
        with open(f, "rb") as src, gzip.open(os.path.join(HERE, runs[-1]["trace"]), "wb") as dst:
            shutil.copyfileobj(src, dst)
    runs.sort(key=lambda r: (r["batch"], r["start"] or ""))
    with open(os.path.join(HERE, "screen_run_log.jsonl"), "w") as fh:
        for r in runs:
            fh.write(json.dumps(r) + "\n")

    ok = [r for r in runs if r["outcome"] == "completed"]
    bad = [r for r in runs if r["outcome"] == "failed"]
    tot = collections.Counter()
    for r in runs:
        for k in USAGE_KEYS + ("total_tokens",):
            tot[k] += r[k]
    models = collections.Counter()
    for r in runs:
        models.update(r["models"])
    batches_done = sorted({r["batch"] for r in ok})
    L = ["# Abstract-screen run log", "",
         "Generated by `build_screen_run_log.py` from the Claude Code subagent transcripts "
         "(session 64912b51-5b5f-4588-a67d-751db700e2fe). One row per agent run in `screen_run_log.jsonl`; "
         "full transcripts in `screen_traces/`.", "",
         "## Summary", "",
         f"- Agent runs: **{len(runs)}** ({len(ok)} completed, {len(bad)} failed and re-run)",
         f"- Batches completed: {len(batches_done)} of 192 (missing: {sorted(set(range(192)) - set(batches_done)) or 'none'})",
         f"- Model(s) sent to the API (assistant turns): " + ", ".join(f"`{m}` × {n}" for m, n in models.most_common()),
         f"- Subagent type: `general-purpose`; reasoning effort recorded in the traces: "
         + ", ".join(sorted({str(r['effort']) for r in runs})),
         f"- First run started {min(r['start'] for r in runs)}; last finished {max(r['end'] for r in runs)} (UTC)", "",
         "| Tokens (all runs) | Count |", "|---|---|"]
    for k in USAGE_KEYS + ("total_tokens",):
        L.append(f"| {k} | {tot[k]:,} |")
    L += ["", "Most of the input is cache reads: each turn re-sends the growing context (instructions + the "
          "~210 abstracts read so far). Completed runs averaged "
          f"{sum(r['total_tokens'] for r in ok)//max(1,len(ok)):,} tokens and "
          f"{sum(r['output_tokens'] for r in ok)//max(1,len(ok)):,} output tokens each.", "",
          "## Failed runs", ""]
    if bad:
        L += ["| Batch | Agent | Started (UTC) | Error |", "|---|---|---|---|"]
        for r in bad:
            L.append(f"| {r['batch']:03d} | {r['agent_id']} | {r['start']} | {(r['error'] or '')[:120]} |")
    else:
        L.append("None.")
    L += ["", "## Prompts", "",
          "Batches 000–008 (first launch, 2026-09-24 ~03:10 EDT) received the full instructions inline; "
          "batch 000 as a foreground pilot. Example (batch 001):", "", "```text",
          next(r["prompt"] for r in runs if r["batch"] == 1), "```", "",
          "All later runs (batches 009–191, including the re-runs of 009–020 after the session limit) "
          "received a one-line pointer to `screen_prompt.md`, e.g.:", "", "```text",
          next(r["prompt"] for r in runs if r["batch"] == 100), "```", "",
          "The task text in `screen_prompt.md` is reproduced verbatim below.", "", "```markdown",
          open(os.path.join(HERE, "screen_prompt.md")).read().rstrip(), "```", "",
          "Note: the \"Files and procedure\" section was appended to `screen_prompt.md` at ~03:40 EDT, "
          "after batches 000–020 had been launched; the task section itself was not changed.", "",
          "## Per-run table", "", "| Batch | Agent | Model | Outcome | API turns | Total tokens | Output tokens | Start (UTC) |",
          "|---|---|---|---|---|---|---|---|"]
    for r in runs:
        L.append(f"| {r['batch']:03d} | {r['agent_id']} | {', '.join(r['models'])} | {r['outcome']} | {r['api_turns']} | "
                 f"{r['total_tokens']:,} | {r['output_tokens']:,} | {r['start']} |")
    open(os.path.join(HERE, "screen_run_log.md"), "w").write("\n".join(L) + "\n")
    print("\n".join(L[:26]))


if __name__ == "__main__":
    main()
